"""Project memory (SRS section 43): typed records, with a readable mirror.

Memory used to be an append-only markdown file. That kept it inspectable but
made it a log: nothing ever superseded anything, a changed convention sat
next to the note it replaced, and the whole file was one undifferentiated
blob in the system prompt.

Records now live in SQLite (`.silkcode/memory.db`, stdlib `sqlite3`, no new
dependency) and are typed:

    preference  how this user likes to work
    fact        something true about the project
    procedure   a command or workflow that works here
    failure     something that went wrong and what fixed it

Writing an already-known note refreshes it instead of duplicating it, and a
note that plainly restates an older one of the same kind supersedes it - the
old record is kept, marked, and stops being shown. That is consolidation done
at write time, where it can be tested, rather than by a background process.

The markdown file survives as a *mirror*: after every write the store renders
itself to `.silkcode/memory.md`, so the human-readable window the old design
prized is still there - it is just generated now, and says so at the top.
A pre-existing hand-written memory.md is imported once, as facts.

Memory is data, never instructions. Whatever this module returns still goes
through the provenance scan in context.py before reaching the system prompt.
"""

from __future__ import annotations

import datetime
import re
import sqlite3
from pathlib import Path

from .workspace import Workspace

MEMORY_RELPATH = ".silkcode/memory.md"
DB_RELPATH = ".silkcode/memory.db"
MAX_MEMORY_CHARS = 8_000

KINDS = ("preference", "fact", "procedure", "failure")

KIND_TITLES = {
    "preference": "Preferences",
    "fact": "Project facts",
    "procedure": "Procedures & commands",
    "failure": "Known failures & fixes",
}

MIRROR_HEADER = (
    "# Project memory\n"
    "# Generated by Silk Code from .silkcode/memory.db - edits here are\n"
    "# overwritten on the next remembered note.\n"
)

# Two notes of the same kind whose word sets overlap at least this much are
# the same knowledge, restated. The newer statement wins.
SUPERSEDE_OVERLAP = 0.75


def memory_path(ws: Workspace) -> Path:
    return ws.root / MEMORY_RELPATH


def db_path(ws: Workspace) -> Path:
    return ws.root / DB_RELPATH


def _words(text: str) -> set[str]:
    return set(re.findall(r"[a-z0-9]+", text.lower()))


def _overlap(a: str, b: str) -> float:
    wa, wb = _words(a), _words(b)
    if not wa or not wb:
        return 0.0
    return len(wa & wb) / len(wa | wb)


def _connect(ws: Workspace) -> sqlite3.Connection:
    from .statedir import ensure_ignored

    path = db_path(ws)
    path.parent.mkdir(parents=True, exist_ok=True)
    ensure_ignored(path.parent)  # memory is ours, not part of their project
    conn = sqlite3.connect(path)
    conn.execute(
        "CREATE TABLE IF NOT EXISTS memory ("
        " id INTEGER PRIMARY KEY,"
        " kind TEXT NOT NULL DEFAULT 'fact',"
        " text TEXT NOT NULL,"
        " created TEXT NOT NULL,"
        " updated TEXT NOT NULL,"
        " status TEXT NOT NULL DEFAULT 'active',"
        " superseded_by INTEGER)"
    )
    return conn


def _import_legacy(ws: Workspace, conn: sqlite3.Connection) -> None:
    """A hand-written memory.md from before the store existed, once.

    Only when the store is empty and the file does not carry our generated
    header - after that the file is the mirror and never read back.
    """
    if conn.execute("SELECT COUNT(*) FROM memory").fetchone()[0]:
        return
    path = memory_path(ws)
    if not path.is_file():
        return
    text = path.read_text(errors="replace")
    if text.startswith("# Project memory"):
        return
    today = datetime.date.today().isoformat()
    for line in text.splitlines():
        line = line.strip().lstrip("-").strip()
        if not line:
            continue
        # the old format stamped entries "- [2026-08-25] note"
        match = re.match(r"^\[(\d{4}-\d{2}-\d{2})\]\s*(.+)$", line)
        stamp, note = (match.group(1), match.group(2)) if match else (today, line)
        if note:
            conn.execute(
                "INSERT INTO memory (kind, text, created, updated) VALUES (?, ?, ?, ?)",
                ("fact", note, stamp, stamp))
    conn.commit()


def _active(conn: sqlite3.Connection) -> list[tuple[int, str, str, str]]:
    return conn.execute(
        "SELECT id, kind, text, updated FROM memory"
        " WHERE status = 'active' ORDER BY id").fetchall()


def _render(records: list[tuple[int, str, str, str]]) -> str:
    """The store as prose, newest last within each kind, capped.

    When over the cap, the oldest records go first - and the text says how
    many, rather than silently forgetting.
    """
    dropped = 0
    while records:
        sections = []
        for kind in KINDS:
            lines = [f"- [{updated}] {text}"
                     for _id, k, text, updated in records if k == kind]
            if lines:
                sections.append(KIND_TITLES[kind] + ":\n" + "\n".join(lines))
        body = "\n\n".join(sections)
        if dropped:
            body = f"... [{dropped} older memories not shown]\n\n" + body
        if len(body) <= MAX_MEMORY_CHARS:
            return body
        records = records[1:]
        dropped += 1
    return ""


def _write_mirror(ws: Workspace, conn: sqlite3.Connection) -> None:
    try:
        body = _render(_active(conn))
        memory_path(ws).write_text(MIRROR_HEADER + ("\n" + body + "\n" if body else ""))
    except OSError:
        pass  # a read-only checkout still gets the database write


def load_memory(ws: Workspace) -> str:
    from .remotews import RemoteWorkspace
    if isinstance(ws, RemoteWorkspace):
        # the repo's memory lives in the sandbox clone, not on this machine,
        # and SQLite cannot reach across; the flat file remains the format
        try:
            if not ws.is_file(MEMORY_RELPATH):
                return ""
            text = ws.read_text(MEMORY_RELPATH).strip()
        except Exception:
            return ""
        if len(text) > MAX_MEMORY_CHARS:
            text = text[-MAX_MEMORY_CHARS:]
            text = "... [older memory truncated]\n" + text
        return text

    if not db_path(ws).is_file() and not memory_path(ws).is_file():
        return ""
    with _connect(ws) as conn:
        _import_legacy(ws, conn)
        return _render(_active(conn))


def remember(ws: Workspace, text: str, kind: str = "fact") -> str:
    from .remotews import RemoteWorkspace

    text = " ".join(text.split())
    if not text:
        return "Nothing to remember (empty text)."
    if kind not in KINDS:
        kind = "fact"
    stamp = datetime.date.today().isoformat()

    if isinstance(ws, RemoteWorkspace):
        # A remote workspace's local root is a scratch directory that stays
        # empty on purpose - the repo lives in the sandbox. Write the note
        # where load_memory reads it.
        entry = f"- [{stamp}] {text}\n"
        try:
            existing = ws.read_text(MEMORY_RELPATH) if ws.is_file(MEMORY_RELPATH) else ""
        except Exception:
            existing = ""
        ws.write_text(MEMORY_RELPATH, existing + entry)
        ws.refresh()  # the file may be new; let the listing pick it up
        return f"Remembered in {MEMORY_RELPATH}: {text}"

    with _connect(ws) as conn:
        _import_legacy(ws, conn)

        # The same note again is a refresh, not a duplicate.
        row = conn.execute(
            "SELECT id FROM memory WHERE status = 'active' AND kind = ? AND text = ?",
            (kind, text)).fetchone()
        if row:
            conn.execute("UPDATE memory SET updated = ? WHERE id = ?", (stamp, row[0]))
            conn.commit()
            _write_mirror(ws, conn)
            return f"Already remembered ({kind}); refreshed: {text}"

        # A restatement supersedes what it restates. The old record is kept
        # and marked, so nothing is destroyed - it just stops being shown.
        superseded = [
            rid for rid, rtext in conn.execute(
                "SELECT id, text FROM memory WHERE status = 'active' AND kind = ?",
                (kind,))
            if _overlap(text, rtext) >= SUPERSEDE_OVERLAP
        ]
        cursor = conn.execute(
            "INSERT INTO memory (kind, text, created, updated) VALUES (?, ?, ?, ?)",
            (kind, text, stamp, stamp))
        for rid in superseded:
            conn.execute(
                "UPDATE memory SET status = 'superseded', superseded_by = ? WHERE id = ?",
                (cursor.lastrowid, rid))
        conn.commit()
        _write_mirror(ws, conn)

    note = f" (supersedes {len(superseded)} earlier note{'s' if len(superseded) > 1 else ''})" \
        if superseded else ""
    return f"Remembered ({kind}){note}: {text}"
